In [1]:
import numpy as np
from numpy.linalg import eig

In [5]:
a = np.array([[0, 2], [2, 3]])
values, vectors = eig(a)
values, vectors

(array([-1.,  4.]),
 array([[-0.89442719, -0.4472136 ],
        [ 0.4472136 , -0.89442719]]))

In [6]:
b = np.array([[2, 2, 4], [1, 3, 5], [2, 3, 4]])
values, vectors = eig(b)
print('value = ', values, 'vector = ', vectors)

value =  [ 8.80916362  0.92620912 -0.73537273] vector =  [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]
